version: '3.8'
services:
  semantic-gaussians:
    build: .
    container_name: semantic-gaussians
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: bash
