scene:
  scene_path: "/workspace/data/flowers"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "./output/EXP_NAME/"
  dynamic: False
  load_iteration: -1
  device: "cuda:0"

render:
  fusion_dir: "./output/my_garden_semantic_features/0.pt"
  model_2d: samclip # choose from openseg, lseg, samclip, vlpart
